steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['installDist']
  dir: 'src/adservice'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/adservice:$TAG_NAME', '.']
  dir: 'src/adservice'
images: ['gcr.io/$PROJECT_ID/adservice:$TAG_NAME']
