steps:

- name: 'gcr.io/cloud-builders/gradle'
  id: 'build-gradle-adservice'
  args: ['installDist']
  dir: 'src/adservice'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-adservice'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/adservice:$TAG_NAME', '.']
  dir: 'src/adservice'
  waitFor: ['build-gradle-adservice']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/cartservice:$TAG_NAME', '.']
  id: 'build-docker-cartservice'
  waitFor: ['-']
  dir: 'src/cartservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-checkoutservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/checkoutservice:$TAG_NAME', '.']
  dir: 'src/checkoutservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-currencyservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/currencyservice:$TAG_NAME', '.']
  dir: 'src/currencyservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-emailservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/emailservice:$TAG_NAME', '.']
  dir: 'src/emailservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-frontend'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/frontend:$TAG_NAME', '.']
  dir: 'src/frontend'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-loadgenerator'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/loadgenerator:$TAG_NAME', '.']
  dir: 'src/loadgenerator'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-paymentservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/paymentservice:$TAG_NAME', '.']
  dir: 'src/paymentservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-productcatalogservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/productcatalogservice:$TAG_NAME', '.']
  dir: 'src/productcatalogservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-recommendationservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/recommendationservice:$TAG_NAME', '.']
  dir: 'src/recommendationservice'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-shippingservice'
  waitFor: ['-']
  args: ['build', '--tag=gcr.io/$PROJECT_ID/shippingservice:$TAG_NAME', '.']
  dir: 'src/shippingservice'
- name: 'gcr.io/cloud-builders/docker'
  id: 'test-docker-shippingservice'
  waitFor: ['build-docker-shippingservice']
  args: ['run', 'gcr.io/$PROJECT_ID/shippingservice:$TAG_NAME', 'go', 'test']
  dir: 'src/shippingservice'

- name: 'gcr.io/cloud-builders/gsutil'
  id: 'copy-manifests'
  waitFor: ['-']
  args: ['cp', '-r', 'release/*', 'gs://$PROJECT_ID-kubernetes-manifests']

options:
  machineType: 'N1_HIGHCPU_8'
timeout: 1200s
images: ['gcr.io/$PROJECT_ID/productcatalogservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/shippingservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/recommendationservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/emailservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/paymentservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/loadgenerator:$TAG_NAME', 'gcr.io/$PROJECT_ID/frontend:$TAG_NAME', 'gcr.io/$PROJECT_ID/currencyservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/adservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/cartservice:$TAG_NAME', 'gcr.io/$PROJECT_ID/checkoutservice:$TAG_NAME']
